version: '3.8'

services:
  # SERVICIO 4: AUTENTICACIÃ“N

  auth-service:
    build: ./servicio4       
    container_name: auth-service
    ports:
      - "5000:5000"          
    environment:
      - FLASK_ENV=production 
    networks:
      - red-microservicios

networks:
  red-microservicios:
    driver: bridge